const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "Bear",
   "filename": "bear.txt",
   "credit_text": "mrf",
   "credit_url": "https://www.asciiart.eu/animals/bears"},
  {"title": "Flowers",
   "filename": "flowers.txt",
   "credit_text": "Joan G. Stark",
   "credit_url": "https://www.asciiart.eu/plants/flowers"},
  {"title": "Monkey w/ Banana",
   "filename": "monkey-eating-banana.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/food-and-drinks/bananas"},
  {"title": "Soccer",
   "filename": "soccer.txt",
   "credit_text": "unknown",
   "credit_url": "https://www.asciiart.eu/sports-and-outdoors/soccer"},
  {"title": "Tasmanian Devil",
   "filename": "tasmanianDevil.txt",
   "credit_text": "akg",
   "credit_url": "https://www.asciiart.eu/animals/marsupials"},
];
